CREATE DATABASE unidas;
GO

USE unidas;
GO

CREATE TABLE PESSOAS(
idPessoa INT PRIMARY KEY IDENTITY(1,1),
nomePessoa VARCHAR(20) NOT NULL
);
GO

CREATE TABLE TELEFONE(
idTelefone INT PRIMARY KEY IDENTITY(1,1),
idPessoa INT FOREIGN KEY REFERENCES PESSOAS(idPessoa),
numeroTelefone CHAR(11) NOT NULL
);
GO

CREATE TABLE EMAIL(
idEmail INT PRIMARY KEY IDENTITY(1,1),
idPessoa INT FOREIGN KEY REFERENCES PESSOAS(idPessoa),
end_email VARCHAR(256) NOT NULL UNIQUE
);
GO

CREATE TABLE CNH(
idCnh INT PRIMARY KEY IDENTITY(1,1),
idPessoa INT FOREIGN KEY REFERENCES PESSOAS(idPessoa),
descricao CHAR(11) NOT NULL UNIQUE
);
GO