CREATE DATABASE LOCADORA;
GO

USE LOCADORA;
GO

CREATE TABLE EMPRESA(
idEmpresa SMALLINT PRIMARY KEY IDENTITY(1,1),
nomeEmpresa VARCHAR(40)
);
GO

CREATE TABLE VEICULOS(
idVeiculo SMALLINT PRIMARY KEY IDENTITY(1,1),
idEmpresa SMALLINT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
placaVeiculo VARCHAR(40) NOT NULL UNIQUE
);
GO